// Generated by DB Solo 5.2.3 on 24/02/2019 at 12:36:17 PM
package DAOs;

public class Carrera
{
  private int idcarrera;
  private String nombrecarrera;
  private String descripcion;
  private Integer duracion;

  //
  // getters / setters
  //

    @Override
    public String toString() {
        return "Carrera{" + "idcarrera=" + idcarrera + ", nombrecarrera=" + nombrecarrera + ", descripcion=" + descripcion + ", duracion=" + duracion + '}';
    }
  

    public Carrera() {
    }
  
  
  public Carrera(String nombrecarrera, String descripcion, Integer duracion)
  {
        this.nombrecarrera = nombrecarrera;
        this.descripcion = descripcion;
        this.duracion = duracion;
  }

    public int getIdcarrera() {
        return this.idcarrera;
    }

  public void setIdcarrera(int idcarrera)
  {
    this.idcarrera = idcarrera;
  }

  public String getNombrecarrera()
  {
    return this.nombrecarrera;
  }

  public void setNombrecarrera(String nombrecarrera)
  {
    this.nombrecarrera = nombrecarrera;
  }

  public String getDescripcion()
  {
    return this.descripcion;
  }

  public void setDescripcion(String descripcion)
  {
    this.descripcion = descripcion;
  }

  public Integer getDuracion()
  {
    return this.duracion;
  }

  public void setDuracion(Integer duracion)
  {
    this.duracion = duracion;
  }
}
