// Generated by DB Solo 5.2.3 on 24/02/2019 at 12:37:59 PM
package DAOs;

public class DAOException extends Exception
{
  public DAOException(String s, Exception e)
  {
    super(s, e);
  }

  public DAOException(String e)
  {
    super(e);
  }

  public DAOException(Exception e)
  {
    super(e);
  }
}
