// Generated by DB Solo 5.2.3 on 24/02/2019 at 12:37:21 PM
package DAOs;

import java.util.Date;
import java.util.List;


public interface ExamenDAO
{
  // CRUD methods
  public Examen getByPrimaryKey(int idexamen) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Examen obj) throws DAOException;

  public int insert(Examen obj) throws DAOException;

  public int delete(Examen obj) throws DAOException;

  // Finders
  public List getByNombreexamen(String nombreexamen) throws DAOException;

  public List getByDescripcion(String descripcion) throws DAOException;

  public List getByFecha(Date fecha) throws DAOException;

  public List getByMateriaIdmateria(int materiaIdmateria)
    throws DAOException;
}
