// Generated by DB Solo 5.2.3 on 24/02/2019 at 12:37:59 PM
package DAOs;

import java.util.List;


public interface MateriaDAO
{
  // CRUD methods
  public Materia getByPrimaryKey(int idmateria) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Materia obj) throws DAOException;

  public int insert(Materia obj) throws DAOException;

  public int delete(Materia obj) throws DAOException;

  // Finders
  public List getByNombremateria(String nombremateria)
    throws DAOException;

  public List getByDescripcion(String descripcion) throws DAOException;

  public List getByCarreraIdcarrera(int carreraIdcarrera)
    throws DAOException;
}
