// Generated by DB Solo 5.2.3 on 24/02/2019 at 01:31:41 PM
package DAOs;

public class Pregunta
{
  private int idpregunta;
  private String nombremateria;
  private String descripcion;
  private String opcion1;
  private String opcion2;
  private String opcion3;
  private String opcion4;
  private String opcion5;
  private String opcioncorrecta;
  private String preguntacol;
  private int examenIdexamen;

    public Pregunta() {
    }

    public Pregunta(String nombremateria, String descripcion, String opcion1, String opcion2, String opcion3, String opcion4, String opcion5, String opcioncorrecta, String preguntacol, int examenIdexamen) {
       
        this.nombremateria = nombremateria;
        this.descripcion = descripcion;
        this.opcion1 = opcion1;
        this.opcion2 = opcion2;
        this.opcion3 = opcion3;
        this.opcion4 = opcion4;
        this.opcion5 = opcion5;
        this.opcioncorrecta = opcioncorrecta;
        this.preguntacol = preguntacol;
        this.examenIdexamen = examenIdexamen;
    }

    @Override
    public String toString() {
        return "Pregunta{" + "idpregunta=" + idpregunta + ", nombremateria=" + nombremateria + ", descripcion=" + descripcion + ", opcion1=" + opcion1 + ", opcion2=" + opcion2 + ", opcion3=" + opcion3 + ", opcion4=" + opcion4 + ", opcion5=" + opcion5 + ", opcioncorrecta=" + opcioncorrecta + ", preguntacol=" + preguntacol + ", examenIdexamen=" + examenIdexamen + '}';
    }

  
  //
  // getters / setters
  //
  public int getIdpregunta()
  {
    return this.idpregunta;
  }

  public void setIdpregunta(int idpregunta)
  {
    this.idpregunta = idpregunta;
  }

  public String getNombremateria()
  {
    return this.nombremateria;
  }

  public void setNombremateria(String nombremateria)
  {
    this.nombremateria = nombremateria;
  }

  public String getDescripcion()
  {
    return this.descripcion;
  }

  public void setDescripcion(String descripcion)
  {
    this.descripcion = descripcion;
  }

  public String getOpcion1()
  {
    return this.opcion1;
  }

  public void setOpcion1(String opcion1)
  {
    this.opcion1 = opcion1;
  }

  public String getOpcion2()
  {
    return this.opcion2;
  }

  public void setOpcion2(String opcion2)
  {
    this.opcion2 = opcion2;
  }

  public String getOpcion3()
  {
    return this.opcion3;
  }

  public void setOpcion3(String opcion3)
  {
    this.opcion3 = opcion3;
  }

  public String getOpcion4()
  {
    return this.opcion4;
  }

  public void setOpcion4(String opcion4)
  {
    this.opcion4 = opcion4;
  }

  public String getOpcion5()
  {
    return this.opcion5;
  }

  public void setOpcion5(String opcion5)
  {
    this.opcion5 = opcion5;
  }

  public String getOpcioncorrecta()
  {
    return this.opcioncorrecta;
  }

  public void setOpcioncorrecta(String opcioncorrecta)
  {
    this.opcioncorrecta = opcioncorrecta;
  }

  public String getPreguntacol()
  {
    return this.preguntacol;
  }

  public void setPreguntacol(String preguntacol)
  {
    this.preguntacol = preguntacol;
  }

  public int getExamenIdexamen()
  {
    return this.examenIdexamen;
  }

  public void setExamenIdexamen(int examenIdexamen)
  {
    this.examenIdexamen = examenIdexamen;
  }
}
