// Generated by DB Solo 5.2.3 on 24/02/2019 at 01:32:24 PM
package DAOs;

import java.util.List;


public interface ProfesorDAO
{
  // CRUD methods
  public Profesor getByPrimaryKey(int noboleta) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Profesor obj) throws DAOException;

  public int insert(Profesor obj) throws DAOException;

  public int delete(Profesor obj) throws DAOException;

  // Finders
  public List getByNombre(String nombre) throws DAOException;

  public List getByMaterno(String materno) throws DAOException;

  public List getByPaterno(String paterno) throws DAOException;

  public List getByDomicilio(String domicilio) throws DAOException;

  public List getByEmail(String email) throws DAOException;

  public List getByIdcarrera(int idcarrera) throws DAOException;

  public List getByIdusuario(int idusuario) throws DAOException;

  public List getByCarreraIdcarrera(int carreraIdcarrera)
    throws DAOException;

  public List getByUsuarioIdusuario(int usuarioIdusuario)
    throws DAOException;
}
