// Generated by DB Solo 5.2.3 on 24/02/2019 at 01:32:24 PM
package DAOs;

public class Profesor
{
  private int noboleta;
  private String nombre;
  private String materno;
  private String paterno;
  private String domicilio;
  private String email;
  private int idcarrera;
  private int idusuario;
  private int carreraIdcarrera;
  private int usuarioIdusuario;

    public Profesor() {
    }

    public Profesor(String nombre, String materno, String paterno, String domicilio, String email, int idcarrera, int idusuario, int carreraIdcarrera, int usuarioIdusuario) {
        
        this.nombre = nombre;
        this.materno = materno;
        this.paterno = paterno;
        this.domicilio = domicilio;
        this.email = email;
        this.idcarrera = idcarrera;
        this.idusuario = idusuario;
        this.carreraIdcarrera = carreraIdcarrera;
        this.usuarioIdusuario = usuarioIdusuario;
    }

    @Override
    public String toString() {
        return "Profesor{" + "noboleta=" + noboleta + ", nombre=" + nombre + ", materno=" + materno + ", paterno=" + paterno + ", domicilio=" + domicilio + ", email=" + email + ", idcarrera=" + idcarrera + ", idusuario=" + idusuario + ", carreraIdcarrera=" + carreraIdcarrera + ", usuarioIdusuario=" + usuarioIdusuario + '}';
    }

  
  //
  // getters / setters
  //
  public int getNoboleta()
  {
    return this.noboleta;
  }

  public void setNoboleta(int noboleta)
  {
    this.noboleta = noboleta;
  }

  public String getNombre()
  {
    return this.nombre;
  }

  public void setNombre(String nombre)
  {
    this.nombre = nombre;
  }

  public String getMaterno()
  {
    return this.materno;
  }

  public void setMaterno(String materno)
  {
    this.materno = materno;
  }

  public String getPaterno()
  {
    return this.paterno;
  }

  public void setPaterno(String paterno)
  {
    this.paterno = paterno;
  }

  public String getDomicilio()
  {
    return this.domicilio;
  }

  public void setDomicilio(String domicilio)
  {
    this.domicilio = domicilio;
  }

  public String getEmail()
  {
    return this.email;
  }

  public void setEmail(String email)
  {
    this.email = email;
  }

  public int getIdcarrera()
  {
    return this.idcarrera;
  }

  public void setIdcarrera(int idcarrera)
  {
    this.idcarrera = idcarrera;
  }

  public int getIdusuario()
  {
    return this.idusuario;
  }

  public void setIdusuario(int idusuario)
  {
    this.idusuario = idusuario;
  }

  public int getCarreraIdcarrera()
  {
    return this.carreraIdcarrera;
  }

  public void setCarreraIdcarrera(int carreraIdcarrera)
  {
    this.carreraIdcarrera = carreraIdcarrera;
  }

  public int getUsuarioIdusuario()
  {
    return this.usuarioIdusuario;
  }

  public void setUsuarioIdusuario(int usuarioIdusuario)
  {
    this.usuarioIdusuario = usuarioIdusuario;
  }
}
