// Generated by DB Solo 5.2.3 on 24/02/2019 at 01:32:57 PM
package DAOs;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


public class RespuestaDAOImpl implements RespuestaDAO
{
  //
  // static data
  //
  protected static List pkColumns = new ArrayList();
  protected static List stdColumns = new ArrayList();
  protected static List allColumns = new ArrayList();
  protected static String tableName = "respuesta";

  static
  {
    pkColumns.add("idrespuesta");
    stdColumns.add("opcionelegida");
    stdColumns.add("pregunta_idpregunta");
    stdColumns.add("resultadoexamen_idresultado");
    allColumns.addAll(pkColumns);
    allColumns.addAll(stdColumns);
  }

  //
  // data
  //
  protected Connection conn = null;

  //
  // construction
  //
  public RespuestaDAOImpl()
  {
    this(null);
  }

  public RespuestaDAOImpl(Connection conn)
  {
    this.conn = conn;
  }

  //
  // CRUD methods
  //
  public Respuesta getByPrimaryKey(int idrespuesta) 
  {
    PreparedStatement ps = null;
    ResultSet rs = null;

    try
    {
      int pos = 1;
      ps = getConn().prepareStatement(DBUtil.select(tableName, allColumns, pkColumns));
      DBUtil.bind(ps, pos++, idrespuesta);
      rs = ps.executeQuery();

      if (rs.next())
      {
        return fromResultSet(rs);
      }
    }
    catch (SQLException e)
    {
        try {
            throw new DAOException(e);
        } catch (DAOException ex) {
            Logger.getLogger(RespuestaDAOImpl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return null;
  }

  public long selectCount() throws DAOException
  {
    PreparedStatement ps = null;
    ResultSet rs = null;

    try
    {
      ps = getConn().prepareStatement("select count(*) from " + tableName);
      rs = ps.executeQuery();

      if (rs.next())
      {
        return rs.getLong(1);
      }
    }
    catch (SQLException e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return 0;
  }

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException
  {
    PreparedStatement ps = null;
    ResultSet rs = null;

    if (!whereStatement.trim().toUpperCase().startsWith("WHERE"))
    {
      whereStatement = " WHERE " + whereStatement;
    }
    else if (whereStatement.startsWith(" ") == false)
    {
      whereStatement = " " + whereStatement;
    }

    try
    {
      ps = getConn().prepareStatement("select count(*) from " + tableName + whereStatement);

      for (int i = 0; i < bindVariables.length; i++)
        DBUtil.bind(ps, i + 1, bindVariables[i]);

      rs = ps.executeQuery();

      if (rs.next())
      {
        return rs.getLong(1);
      }
    }
    catch (SQLException e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return 0;
  }

  public List selectAll() throws DAOException
  {
    List ret = new ArrayList();
    PreparedStatement ps = null;
    ResultSet rs = null;

    try
    {
      ps = getConn().prepareStatement(DBUtil.select(tableName, allColumns));
      rs = ps.executeQuery();

      while (rs.next())
        ret.add(fromResultSet(rs));
    }
    catch (SQLException e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return ret;
  }

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException
  {
    List ret = new ArrayList();
    PreparedStatement ps = null;
    ResultSet rs = null;

    if (!whereStatement.trim().toUpperCase().startsWith("WHERE"))
    {
      whereStatement = " WHERE " + whereStatement;
    }
    else if (whereStatement.startsWith(" ") == false)
    {
      whereStatement = " " + whereStatement;
    }

    try
    {
      ps = getConn().prepareStatement(DBUtil.select(tableName, allColumns) + whereStatement);

      for (int i = 0; i < bindVariables.length; i++)
        DBUtil.bind(ps, i + 1, bindVariables[i]);

      rs = ps.executeQuery();

      while (rs.next())
        ret.add(fromResultSet(rs));
    }
    catch (SQLException e)
    {
      throw new DAOException("Error in select(), table = " + tableName, e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return ret;
  }

  public int update(Respuesta obj) 
  {
    PreparedStatement ps = null;
    int pos = 1;

    try
    {
      ps = getConn().prepareStatement(DBUtil.update(tableName, stdColumns, pkColumns));
      pos = bindStdColumns(ps, obj, pos);
      bindPrimaryKey(ps, obj, pos);

      int rowCount = ps.executeUpdate();

      if (rowCount != 1)
      {
        throw new DAOException("Error updating " + obj.getClass() + " in " + tableName +
          ", affected rows = " + rowCount);
      }

      return rowCount;
    }
    catch (SQLException e)
    {
        try {
            throw new DAOException(e);
        } catch (DAOException ex) {
            Logger.getLogger(RespuestaDAOImpl.class.getName()).log(Level.SEVERE, null, ex);
        }
    } catch (DAOException ex) {
          Logger.getLogger(RespuestaDAOImpl.class.getName()).log(Level.SEVERE, null, ex);
      }
    finally
    {
      DBUtil.close(ps, null);
    }
      return 0;
  }

  public int insert(Respuesta obj)
  {
    PreparedStatement ps = null;
    int pos = 1;

    try
    {
      ps = getConn().prepareStatement(DBUtil.insert(tableName, pkColumns, stdColumns));
      pos = bindPrimaryKey(ps, obj, pos);
      bindStdColumns(ps, obj, pos);

      int rowCount = ps.executeUpdate();

      if (rowCount != 1)
      {
        throw new DAOException("Error inserting " + obj.getClass() + " in " + tableName +
          ", affected rows = " + rowCount);
      }

      return rowCount;
    }
    catch (SQLException e)
    {
        try {
            throw new DAOException(e);
        } catch (DAOException ex) {
            Logger.getLogger(RespuestaDAOImpl.class.getName()).log(Level.SEVERE, null, ex);
        }
    } catch (DAOException ex) {
          Logger.getLogger(RespuestaDAOImpl.class.getName()).log(Level.SEVERE, null, ex);
      }
    finally
    {
      DBUtil.close(ps, null);
    }
      return 0;
  }

  public int delete(Respuesta obj) 
  {
    PreparedStatement ps = null;

    try
    {
      ps = getConn().prepareStatement(DBUtil.delete(tableName, pkColumns));
      bindPrimaryKey(ps, obj, 1);

      int rowCount = ps.executeUpdate();

      if (rowCount != 1)
      {
        throw new DAOException("Error deleting " + obj.getClass() + " in " + tableName +
          ", affected rows = " + rowCount);
      }

      return rowCount;
    }
    catch (SQLException e)
    {
        try {
            throw new DAOException(e);
        } catch (DAOException ex) {
            Logger.getLogger(RespuestaDAOImpl.class.getName()).log(Level.SEVERE, null, ex);
        }
    } catch (DAOException ex) {
          Logger.getLogger(RespuestaDAOImpl.class.getName()).log(Level.SEVERE, null, ex);
      }
    finally
    {
      DBUtil.close(ps, null);
    }
      return 0;
  }

  //
  // finders
  //
  public List getByOpcionelegida(Integer opcionelegida)
    throws DAOException
  {
    PreparedStatement ps = null;
    ResultSet rs = null;
    List ret = new ArrayList();

    try
    {
      if (null == opcionelegida)
      {
        ps = getConn()
               .prepareStatement(DBUtil.selectNull(tableName, allColumns,
              Arrays.asList(new String[]{ "opcionelegida" })));
      }
      else
      {
        ps = getConn()
               .prepareStatement(DBUtil.select(tableName, allColumns,
              Arrays.asList(new String[]{ "opcionelegida" })));
        DBUtil.bind(ps, 1, opcionelegida);
      }

      rs = ps.executeQuery();

      while (rs.next())
        ret.add(fromResultSet(rs));
    }
    catch (SQLException e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return ret;
  }

  public List getByPreguntaIdpregunta(int preguntaIdpregunta)
    throws DAOException
  {
    PreparedStatement ps = null;
    ResultSet rs = null;
    List ret = new ArrayList();

    try
    {
      ps = getConn()
             .prepareStatement(DBUtil.select(tableName, allColumns,
            Arrays.asList(new String[]{ "pregunta_idpregunta" })));
      DBUtil.bind(ps, 1, preguntaIdpregunta);
      rs = ps.executeQuery();

      while (rs.next())
        ret.add(fromResultSet(rs));
    }
    catch (SQLException e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return ret;
  }

  public List getByResultadoexamenIdresultado(int resultadoexamenIdresultado)
    throws DAOException
  {
    PreparedStatement ps = null;
    ResultSet rs = null;
    List ret = new ArrayList();

    try
    {
      ps = getConn()
             .prepareStatement(DBUtil.select(tableName, allColumns,
            Arrays.asList(new String[]{ "resultadoexamen_idresultado" })));
      DBUtil.bind(ps, 1, resultadoexamenIdresultado);
      rs = ps.executeQuery();

      while (rs.next())
        ret.add(fromResultSet(rs));
    }
    catch (SQLException e)
    {
      throw new DAOException(e);
    }
    finally
    {
      DBUtil.close(ps, rs);
    }

    return ret;
  }

  //
  // helpers
  //
  protected int bindPrimaryKey(PreparedStatement ps, Respuesta obj, int pos)
    throws SQLException
  {
    DBUtil.bind(ps, pos++, obj.getIdrespuesta());

    return pos;
  }

  protected int bindStdColumns(PreparedStatement ps, Respuesta obj, int pos)
    throws SQLException
  {
    DBUtil.bind(ps, pos++, obj.getOpcionelegida());
    DBUtil.bind(ps, pos++, obj.getPreguntaIdpregunta());
    DBUtil.bind(ps, pos++, obj.getResultadoexamenIdresultado());

    return pos;
  }

  protected Respuesta fromResultSet(ResultSet rs) throws SQLException
  {
    Respuesta obj = new Respuesta();

    obj.setIdrespuesta(DBUtil.getInt(rs, "idrespuesta"));
    obj.setOpcionelegida(DBUtil.getInteger(rs, "opcionelegida"));
    obj.setPreguntaIdpregunta(DBUtil.getInt(rs, "pregunta_idpregunta"));
    obj.setResultadoexamenIdresultado(DBUtil.getInt(rs, "resultadoexamen_idresultado"));

    return obj;
  }

  protected Connection getConn() {
        return conn = Conexion.getConexion();
    }
  
  public static void main(String[] args) {

        try {
            System.out.println("nada");
            UsuarioDAOImpl dao=new UsuarioDAOImpl();
            dao.insert(new Usuario("jonathan", "jonathan", 2));
            System.out.println(Arrays.toString(dao.selectAll().toArray()));
        } catch (DAOException ex) {
            Logger.getLogger(AlumnoDAOImpl.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
