// Generated by DB Solo 5.2.3 on 24/02/2019 at 01:33:27 PM
package DAOs;

import java.util.List;


public interface ResultadoexamenDAO
{
  // CRUD methods
  public Resultadoexamen getByPrimaryKey(int idresultado)
    throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Resultadoexamen obj) throws DAOException;

  public int insert(Resultadoexamen obj) throws DAOException;

  public int delete(Resultadoexamen obj) throws DAOException;

  // Finders
  public List getByCalificacion(int calificacion) throws DAOException;

  public List getByFecha(String fecha) throws DAOException;

  public List getByMateriaIdmateria(int materiaIdmateria)
    throws DAOException;

  public List getByAlumnoNoboleta(int alumnoNoboleta) throws DAOException;
}
