// Generated by DB Solo 5.2.3 on 24/02/2019 at 01:34:02 PM
package DAOs;

public class Usuario
{
  private int idusuario;
  private String nombreUsuario;
  private String password;
  private Integer tipoUsuario;

    @Override
    public String toString() {
        return "Usuario{" + "idusuario=" + idusuario + ", nombreUsuario=" + nombreUsuario + ", password=" + password + ", tipoUsuario=" + tipoUsuario + '}';
    }

    public Usuario(String nombreUsuario, String password, Integer tipoUsuario) {
        
        this.nombreUsuario = nombreUsuario;
        this.password = password;
        this.tipoUsuario = tipoUsuario;
    }

    public Usuario() {
    }

  
  //
  // getters / setters
  //
  public int getIdusuario()
  {
    return this.idusuario;
  }

  public void setIdusuario(int idusuario)
  {
    this.idusuario = idusuario;
  }

  public String getNombreUsuario()
  {
    return this.nombreUsuario;
  }

  public void setNombreUsuario(String nombreUsuario)
  {
    this.nombreUsuario = nombreUsuario;
  }

  public String getPassword()
  {
    return this.password;
  }

  public void setPassword(String password)
  {
    this.password = password;
  }

  public Integer getTipoUsuario()
  {
    return this.tipoUsuario;
  }

  public void setTipoUsuario(Integer tipoUsuario)
  {
    this.tipoUsuario = tipoUsuario;
  }
}
