// Generated by DB Solo 5.2.3 on 24/02/2019 at 01:34:02 PM
package DAOs;

import java.util.List;


public interface UsuarioDAO
{
  // CRUD methods
  public Usuario getByPrimaryKey(int idusuario) throws DAOException;

  public List selectAll() throws DAOException;

  public List select(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public long selectCount() throws DAOException;

  public long selectCount(String whereStatement, Object[] bindVariables)
    throws DAOException;

  public int update(Usuario obj) throws DAOException;

  public int insert(Usuario obj) throws DAOException;

  public int delete(Usuario obj) throws DAOException;

  // Finders
  public List getByNombreUsuario(String nombreUsuario)
    throws DAOException;

  public List getByPassword(String password) throws DAOException;

  public List getByTipoUsuario(Integer tipoUsuario) throws DAOException;
}
