-- MySQL Script generated by MySQL Workbench
-- Sun Feb 24 10:12:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema instituto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `instituto` ;

-- -----------------------------------------------------
-- Schema instituto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instituto` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `instituto` ;

-- -----------------------------------------------------
-- Table `instituto`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`alumno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `instituto`.`alumno` (
  `noboleta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `materno` VARCHAR(30) NOT NULL,
  `paterno` VARCHAR(30) NOT NULL,
  `domicilio` VARCHAR(150) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `idcarrera` INT(11) NOT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`noboleta`),
  INDEX `idcarrera` (`idcarrera` ASC),
  INDEX `alumno_ibfk_2_idx` (`idusuario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1002
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `instituto`.`carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`carrera` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `instituto`.`carrera` (
  `idcarrera` INT(11) NOT NULL AUTO_INCREMENT,
  `nombrecarrera` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `duracion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idcarrera`))
ENGINE = InnoDB
AUTO_INCREMENT = 1005
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `instituto`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`profesor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `instituto`.`profesor` (
  `noboleta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `materno` VARCHAR(30) NOT NULL,
  `paterno` VARCHAR(30) NOT NULL,
  `domicilio` VARCHAR(150) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `idcarrera` INT(11) NOT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`noboleta`),
  INDEX `idcarrera` (`idcarrera` ASC),
  INDEX `alumno_ibfk_2_idx` (`idusuario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1002
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `instituto`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instituto`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `instituto`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(30) NOT NULL,
  `password` CHAR(64) NOT NULL,
  `tipo_usuario` INT(11) NULL DEFAULT 1,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
USE `instituto` ;

-- -----------------------------------------------------
-- procedure spAlumnosPorCarrera
-- -----------------------------------------------------

USE `instituto`;
DROP procedure IF EXISTS `instituto`.`spAlumnosPorCarrera`;
SHOW WARNINGS;

DELIMITER $$
USE `instituto`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `spAlumnosPorCarrera`()
begin
SELECT count(*) as Alumnos, c.descripcion as carrera from alumno a,
carrera c where a.idcarrera = c.idcarrera group by c.idcarrera order by Alumnos desc;
end$$

DELIMITER ;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
