package model.entities;
// Generated 29/05/2019 10:03:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Proxy;

/**
 * Artist generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name="artist"
    ,schema="public"
)
public class Artist  implements java.io.Serializable {


     private int artistid;
     private String name;
     private Set<Album> albums = new HashSet<Album>(0);

    public Artist() {
    }

	
    public Artist(int artistid) {
        this.artistid = artistid;
    }
    public Artist(int artistid, String name, Set<Album> albums) {
       this.artistid = artistid;
       this.name = name;
       this.albums = albums;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="artistid", unique=true, nullable=false)
    public int getArtistid() {
        return this.artistid;
    }
    
    public void setArtistid(int artistid) {
        this.artistid = artistid;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="artist")
    public Set<Album> getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Set<Album> albums) {
        this.albums = albums;
    }




}


