package model.entities;
// Generated 29/05/2019 10:03:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Proxy;

/**
 * Genre generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name="genre"
    ,schema="public"
)
public class Genre  implements java.io.Serializable {


     private int genreid;
     private String name;
     private Set<Track> tracks = new HashSet<Track>(0);

    public Genre() {
    }

	
    public Genre(int genreid) {
        this.genreid = genreid;
    }
    public Genre(int genreid, String name, Set<Track> tracks) {
       this.genreid = genreid;
       this.name = name;
       this.tracks = tracks;
    }
   
     @Id 
@GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="genreid", unique=true, nullable=false)
    public int getGenreid() {
        return this.genreid;
    }
    
    public void setGenreid(int genreid) {
        this.genreid = genreid;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="genre")
    public Set<Track> getTracks() {
        return this.tracks;
    }
    
    public void setTracks(Set<Track> tracks) {
        this.tracks = tracks;
    }




}


