package model.entities;
// Generated 29/05/2019 10:03:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Proxy;

/**
 * Invoiceline generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name="invoiceline"
    ,schema="public"
)
public class Invoiceline  implements java.io.Serializable {


     private int invoicelineid;
     private Invoice invoice;
     private Track track;
     private BigDecimal unitprice;
     private Short quantity;

    public Invoiceline() {
    }

	
    public Invoiceline(int invoicelineid, Invoice invoice, Track track) {
        this.invoicelineid = invoicelineid;
        this.invoice = invoice;
        this.track = track;
    }
    public Invoiceline(int invoicelineid, Invoice invoice, Track track, BigDecimal unitprice, Short quantity) {
       this.invoicelineid = invoicelineid;
       this.invoice = invoice;
       this.track = track;
       this.unitprice = unitprice;
       this.quantity = quantity;
    }
   
     @Id 
@GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="invoicelineid", unique=true, nullable=false)
    public int getInvoicelineid() {
        return this.invoicelineid;
    }
    
    public void setInvoicelineid(int invoicelineid) {
        this.invoicelineid = invoicelineid;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="invoiceid", nullable=false)
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="trackid", nullable=false)
    public Track getTrack() {
        return this.track;
    }
    
    public void setTrack(Track track) {
        this.track = track;
    }

    
    @Column(name="unitprice", precision=131089, scale=0)
    public BigDecimal getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }

    
    @Column(name="quantity")
    public Short getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Short quantity) {
        this.quantity = quantity;
    }




}


