package model.entities;
// Generated 29/05/2019 10:03:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mediatype generated by hbm2java
 */
@Entity
@Table(name="mediatype"
    ,schema="public"
)
public class Mediatype  implements java.io.Serializable {


     private int mediatypeid;
     private String name;
     private Set<Playlisttrack> playlisttracks = new HashSet<Playlisttrack>(0);
     private Set<Track> tracks = new HashSet<Track>(0);
     private Set<Playlist> playlists = new HashSet<Playlist>(0);

    public Mediatype() {
    }

	
    public Mediatype(int mediatypeid) {
        this.mediatypeid = mediatypeid;
    }
    public Mediatype(int mediatypeid, String name, Set<Playlisttrack> playlisttracks, Set<Track> tracks, Set<Playlist> playlists) {
       this.mediatypeid = mediatypeid;
       this.name = name;
       this.playlisttracks = playlisttracks;
       this.tracks = tracks;
       this.playlists = playlists;
    }
   
     @Id 

    
    @Column(name="mediatypeid", unique=true, nullable=false)
    public int getMediatypeid() {
        return this.mediatypeid;
    }
    
    public void setMediatypeid(int mediatypeid) {
        this.mediatypeid = mediatypeid;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mediatype")
    public Set<Playlisttrack> getPlaylisttracks() {
        return this.playlisttracks;
    }
    
    public void setPlaylisttracks(Set<Playlisttrack> playlisttracks) {
        this.playlisttracks = playlisttracks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mediatype")
    public Set<Track> getTracks() {
        return this.tracks;
    }
    
    public void setTracks(Set<Track> tracks) {
        this.tracks = tracks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mediatype")
    public Set<Playlist> getPlaylists() {
        return this.playlists;
    }
    
    public void setPlaylists(Set<Playlist> playlists) {
        this.playlists = playlists;
    }




}


