package model.entities;
// Generated 29/05/2019 10:03:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Proxy;

/**
 * Playlisttrack generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name="playlisttrack"
    ,schema="public"
)
public class Playlisttrack  implements java.io.Serializable {


     private int playlisttrackid;
     private Album album;
     private Mediatype mediatype;

    public Playlisttrack() {
    }

    public Playlisttrack(int playlisttrackid, Album album, Mediatype mediatype) {
       this.playlisttrackid = playlisttrackid;
       this.album = album;
       this.mediatype = mediatype;
    }
   
     @Id 
@GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="playlisttrackid", unique=true, nullable=false)
    public int getPlaylisttrackid() {
        return this.playlisttrackid;
    }
    
    public void setPlaylisttrackid(int playlisttrackid) {
        this.playlisttrackid = playlisttrackid;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="playlistid", nullable=false)
    public Album getAlbum() {
        return this.album;
    }
    
    public void setAlbum(Album album) {
        this.album = album;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="trackid", nullable=false)
    public Mediatype getMediatype() {
        return this.mediatype;
    }
    
    public void setMediatype(Mediatype mediatype) {
        this.mediatype = mediatype;
    }




}


