package entities;
// Generated 7/04/2019 03:22:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Movimientoarticulo generated by hbm2java
 */
@Entity
@Table(name="movimientoarticulo"
    ,catalog="inventarios"
)
public class Movimientoarticulo  implements java.io.Serializable {


     private Integer folio;
     private Articulo articulo;
     private String fecha;
     private String tipo;
     private Integer cantidad;

    public Movimientoarticulo() {
    }

	
    public Movimientoarticulo(Articulo articulo, String fecha, String tipo) {
        this.articulo = articulo;
        this.fecha = fecha;
        this.tipo = tipo;
    }
    public Movimientoarticulo(Articulo articulo, String fecha, String tipo, Integer cantidad) {
       this.articulo = articulo;
       this.fecha = fecha;
       this.tipo = tipo;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="folio", unique=true, nullable=false)
    public Integer getFolio() {
        return this.folio;
    }
    
    public void setFolio(Integer folio) {
        this.folio = folio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="claveart", nullable=false)
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }

    
    @Column(name="fecha", nullable=false, length=40)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="tipo", nullable=false, length=100)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


